apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cell-2
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/kszpakowski/crossplane-demo.git
    path: "./gitops/cells/2"
    directory:
      recurse: true
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
