apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: crossplane-system
    server: https://kubernetes.default.svc
  source:
    repoURL: https://charts.crossplane.io/stable
    targetRevision: "1.18.2"
    chart: crossplane
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
